routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => '', 'namespace' => 'User'], function () {
    Route::post('/l', 'UserController@postlogin')->name('User.postlogin');
    Route::get('login', 'UserController@login')->name('User.login');
    Route::post('/register', 'UserController@postpegister')->name('User.postpegister');
    Route::get('/logout', 'UserController@getlogout')->name('User.logout');
    Route::post('/change_pasword', 'UserController@post_change_pasword')->name('User.post_change_pasword');
    Route::post('/forgot_password', 'UserController@post_password')->name('User.post_password');
    Route::get('/forgotpass', 'UserController@forgotpass')->name('User.forgotpass');
    Route::post('/avatar/{customer}', 'UserController@postavatar')->name('customer.avatar');
    Route::get('/information', 'UserController@information')->name('User.information');

    Route::get('/code', 'UserController@get_code')->name('User.get_code');
    Route::post('/code', 'UserController@post_code')->name('User.post_code');

    Route::get('/', 'UserController@home')->name('User.home');
    Route::get('search_home', 'UserController@search_home')->name('User.search_home');
    Route::get('guideview','UserController@guideview')->name('guideview');


    Route::get('tour_details/{id}', 'UserController@tour_details')->name('User.tour_details');
    Route::post('tour_details_post', 'UserController@tour_details_post')->name('User.tour_details_post');
     Route::post('rating_post','UserController@rating_post')->name('User.rating_post');

    Route::get('blog_single/{id}', 'UserController@blog_single')->name('User.blog_single');
    Route::get('about', 'UserController@about')->name('User.about');
    Route::get('blog', 'UserController@blog')->name('User.blog');
    Route::get('search_blogs', 'UserController@search_blogs')->name('User.search_blogs');

    Route::get('contact', 'UserController@contact')->name('User.contact');
    Route::post('contact_post', 'UserController@contact_post')->name('User.contact_post');

    Route::get('faq', 'UserController@faq')->name('User.faq');
    Route::get('service', 'UserController@service')->name('User.service');
    Route::get('tour_packages/{id}', 'UserController@tour_packages')->name('User.tour_packages');
    Route::get('error', 'UserController@error')->name('User.error');
    Route::get('gallery', 'UserController@gallery')->name('User.gallery');
    Route::post('ajax-post', 'UserController@ajax_post')->name('ajax-post');
    Route::get('seach_information','UserController@seach_information')->name('User.seach_information');
});
// -----------------------admin-------------------------------
Route::group(['prefix'=>'admin','namespace' => 'Admin','as' =>'admin.'], function () {
    Route::get('changestatus/{id}', 'customerController@changestatus')->name('changestatus');
    Route::get('/login', 'AdminLoginController@getlogin')->name('getlogin');
    Route::post('/login', 'AdminLoginController@postlogin')->name('postlogin');
    Route::get('/error', 'customerController@error')->name('error');
    Route::post('/avatar/{customer}', 'customerController@postavatar')->name('customer.avatar');
    Route::get('/forgot_password', 'AdminLoginController@get_password')->name('get_password');
    Route::post('/forgot_password', 'AdminLoginController@post_password')->name('post_password');
    Route::get('/password', 'AdminLoginController@get_code')->name('get_code');
    Route::post('/password', 'AdminLoginController@post_code')->name('post_code');
    Route::get('/register', 'RegisterController@get_register')->name('get_register');
    Route::post('/register', 'RegisterController@post_register')->name('post_register');
    Route::post('/change_pasword', 'AdminLoginController@post_change_pasword')->name('post_change_pasword');
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/', 'AdminLoginController@dashboard')->name('index');
        Route::resources([
            'category' => 'CategoryController',
            'tag' => 'TagController',
            'tour' => 'TourController',
            'customer' => 'customerController',
            'role' => 'RoleController',
            'gallery' => 'GalleryController',
            'role_assignment' => 'Role_AssignmentController',
            'contact' => 'contactController',
            'customer_service' => 'CustomerServiceController',
            'permission' => 'permissionController',

            // 'role_permission' => 'role_permissionController',
            'payment' => 'PaymentController',
            'order' => 'OrderController',
            'service' => 'ServiceController',
            'guide' => 'GuideController',
            'blog' => 'BlogController',
            'rating' => 'RatingController',
        ]);
         Route::get('orderview','OrderController@orderview')->name('orderview');
         Route::get('search_category','CategoryController@search_category')->name('search_category');
         Route::get('search_tag','TagController@search_tag')->name('search_tag');
         Route::get('search_payment','PaymentController@search_payment')->name('search_payment');
         Route::get('search_guide','GuideController@search_guide')->name('search_guide');
         Route::get('search_rating','RatingController@search_rating')->name('search_rating');
         Route::get('search_contact','contactController@search_contact')->name('search_contact');
         Route::get('search_tour','TourController@search_tour')->name('search_tour');
         Route::get('search_blog','BlogController@search_blog')->name('search_blog');
         Route::get('search_gallery','GalleryController@search_gallery')->name('search_gallery');
         Route::get('search_customer','customerController@search_customer')->name('search_customer');
         Route::get('search_customer_service','CustomerServiceController@search_customer_service')->name('search_customer_service');
         Route::get('search_role_assignment','Role_AssignmentController@search_role_assignment')->name('search_role_assignment');
         Route::get('seach_role','RoleController@seach_role')->name('seach_role');
         Route::get('search_service','ServiceController@search_service')->name('search_service');
         Route::get('seach_order','OrderController@seach_order')->name('seach_order');
         Route::get('seach_permission','OrderController@seach_permission')->name('seach_permission');

        Route::get('/logout', 'AdminLoginController@getLogout')->name('getlogout');
    });
});

app/Models/customer_service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\contact;
use App\Models\customer_service;

class customer_service extends Model
{
    protected $fillable = ['contact_id','content'];
    public function add(){
    $arr=[
        'contact_id'=>request()->contact_id,
        // 'date_rep'=>request()->date_rep,
        'content'=>request()->content,
    ];
        $model = $this->create($arr);
        return $model;
    }
    public function edit($id){
    $arr=[
        'contact_id'=>request()->contact_id,
        // 'date_rep'=>request()->date_rep,
        'content'=>request()->content,
    ];
    $model =$this->where('id',$id)->update($arr);
        return $model;
    }
    public function customer_service(){
        return $this->hasMany(customer_service::class,'contact_id','id');
    }
    public function contact(){
        return $this->belongsTo(contact::class,'contact_id','id');
    }
}

app/Http/Controllers/Admin/CustomerServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\customer_service;
use App\Models\contact;
use App\Models\customer;
use Illuminate\Http\Request;
use Mail;
use App\Mail\ContactMail;

class CustomerServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customer_service = customer_service::paginate(10);

        return view('admin.page.customer_service.list',compact('customer_service'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request )
    {
        // $request->contact;
        // $customer_service = customer_service::all();
        $contact = contact::find($request->contact);
        return  view('admin.page.customer_service.create',compact('contact'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,customer_service $customer_service)
    {
        $data = [
            'email' =>  $request->email,
            'content' => $request->content,
        ];
        $email = $request->email;
        Mail::send('admin.mailcontact', $data, function ($message) use ($email) {
            $message->from('wendtravel68@gmail.com');
            $message->to($email, 'Phản hồi khách hàng!')->subject('Phản hồi khách hàng!');
        });
        $model = $customer_service->add();

        if ($model) {
            return redirect()->route('admin.customer_service.index')->with('yes', 'them thanh cong ');
        } else {
            return redirect()->back()->with('no', 'toang ');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\customer_service  $customer_service
     * @return \Illuminate\Http\Response
     */
    public function show(customer_service $customer_service)
    {
        //
    }
      public function search_customer_service(Request $request)
    {
        $search =$request->get('search');
            $customer_service = customer_service::where('contact_id','like','%' .$search . '%')->paginate(10);
            return view('admin.page.customer_service.list',compact('customer_service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\customer_service  $customer_service
     * @return \Illuminate\Http\Response
     */
    public function edit(customer_service $customer_service, contact $contact)
    {
        // dd($customer_service->contact);
        return view ('admin.page.customer_service.update',[
            'customer_service' =>$customer_service,
            'contact' =>$contact->all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\customer_service  $customer_service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, customer_service $customer_service)
    {
        $customer_service->edit($customer_service->id);
        return redirect()->route('admin.customer_service.index')->with('ss','caa nhat thanh cong!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\customer_service  $customer_service
     * @return \Illuminate\Http\Response
     */
    public function destroy(customer_service $customer_service)
    {
        if ($customer_service ) {
            $customer_service->delete();
            return redirect()->route('admin.customer_service.index')->with('yes','xoa thanh cong ');
        }else{
            return redirect()->back()->with('no','danh muc co trong bang con khong the xoa ');
        }
    }
}

resources/views/admin/page/customer_service/create.blade.php
@extends('admin/main')
@section('content')
 <!-- Main content -->
 <div class="content-wrapper">
  <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Add</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Role Assignment</li>
        </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section>
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Thêm mới</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="POST" action="{{ route('admin.customer_service.store') }}"  enctype="multipart/form-data">
                @csrf

                <div class="card-body">
                      <!-- select -->

                  <div class="form-group">
                    <label for="exampleInputEmail1">Email:</label>
                     <input type="text" class="form-control d-none" id="contact_id" name="contact_id"  value="{{$contact->id}}"  >
                    <input type="hidden" class="form-control d-none"  name="email"  value="{{$contact->email}}"  >
                    <h6>{{ $contact->email }}</h6>
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">Contact </label>
                    <input type="text" class="form-control" id="content" name="content" placeholder="content">
                  </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
              </form>
            </div>
            <!-- /.card -->

          </div>
    </section>
</div>
@endsection

resources/views/admin/page/customer_service/list.blade.php
@extends('admin/main')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Customer Service</h1>
                     </div><!-- /.col -->

          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Customer Service</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
 <!-- Main content -->
   <section class="content">
      <div class="container-fluid">
        <!-- Info boxes -->
            <div class="card">
              <div class="card-header border-transparent">
                <h3 class="card-title">Customer Service</h3>

              </div>
                <form class="form-inline ml-3" action="{{ route('admin.search_customer_service') }}" method="GET">
              <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" name="search" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
            </form>

              <!-- /.card-header -->
              <div class="card-body ">
                <div class="table-responsive">
                  <table class="table m-0" id="example1">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>Contact Id</th>
                      <th>Date Rep</th>
                      <th>Content</th>
                      <th>
                        <a href="{{ route('admin.customer_service.create') }}" class="btn btn-xs btn-primary">Thêm</a>
                      </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($customer_service as $model)
                      <tr>
                        <td>{{ $model->id }}</td>
                        <td>{{ $model->contact->email }}</td>
                        <td>{{ $model->created_at }}</td>
                        <td>{{ $model->content }}</td>
                        <td>
                            <a href="{{ route('admin.customer_service.edit',$model->id) }}" class="btn btn-xs btn-primary ">Sửa</a>
                            <form action="{{ route('admin.customer_service.destroy',$model->id) }}" method="POST" accept-charset="utf-8">
                            @csrf @method('DELETE')
                            <button type="submit" class="btn btn-xs btn-danger  " onclick="return confirm('Bạn có chắc muốn xóa không') " >Xóa</button>
                            </form>
                        </td>
                      </tr>
                    @endforeach
                    </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">
                <div class="btn btn-sm  float-right">
                        {{ $customer_service->links() }}
                    </div>
              </div>
              <!-- /.card-footer -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
@endsection
@section('data_table')
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
@endsection

resources/views/admin/page/customer_service/update.blade.php
@extends('admin/main')
@section('content')
 <!-- Main content -->
 <div class="content-wrapper">
  <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Add</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Role Assignment</li>
        </ol>
        </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>  
    <section>
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Thêm mới</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="POST" action="{{ route('customer_service.store',$customer_service->id) }}"  enctype="multipart/form-data">
                @csrf @method('PUT')

                <div class="card-body">
                      <!-- select -->
                  <div class="form-group">
                    <label>Conatct Name</label>
                    <select class="form-control" name="contact_id">
                      <option value="{{$customer_service->contact_id}}">{{$customer_service->contact->content}}</option>
                        @foreach($contact as $val)
                        @if ($customer_service->contact_id!=$val->id)
                        <option value="{{$val->id}}">{{$val->content}}</option>
                        @endif
                        @endforeach
                    </select>
                  </div>
                   <div class="form-group">
                    <label for="exampleInputEmail1">Date Rep </label>
                    <input type="text" class="form-control" id="date_rep" name="date_rep" placeholder="Title">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Contact </label>
                    <input type="text" class="form-control" id="content" name="content" placeholder="Title">
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
              </form>
            </div>
            <!-- /.card -->

          </div>
    </section>
</div>
@endsection