routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => '', 'namespace' => 'User'], function () {
    Route::post('/l', 'UserController@postlogin')->name('User.postlogin');
    Route::get('login', 'UserController@login')->name('User.login');
    Route::post('/register', 'UserController@postpegister')->name('User.postpegister');
    Route::get('/logout', 'UserController@getlogout')->name('User.logout');
    Route::post('/change_pasword', 'UserController@post_change_pasword')->name('User.post_change_pasword');
    Route::post('/forgot_password', 'UserController@post_password')->name('User.post_password');
    Route::get('/forgotpass', 'UserController@forgotpass')->name('User.forgotpass');
    Route::post('/avatar/{customer}', 'UserController@postavatar')->name('customer.avatar');
    Route::get('/information', 'UserController@information')->name('User.information');

    Route::get('/code', 'UserController@get_code')->name('User.get_code');
    Route::post('/code', 'UserController@post_code')->name('User.post_code');

    Route::get('/', 'UserController@home')->name('User.home');
    Route::get('search_home', 'UserController@search_home')->name('User.search_home');
    Route::get('guideview','UserController@guideview')->name('guideview');


    Route::get('tour_details/{id}', 'UserController@tour_details')->name('User.tour_details');
    Route::post('tour_details_post', 'UserController@tour_details_post')->name('User.tour_details_post');
     Route::post('rating_post','UserController@rating_post')->name('User.rating_post');

    Route::get('blog_single/{id}', 'UserController@blog_single')->name('User.blog_single');
    Route::get('about', 'UserController@about')->name('User.about');
    Route::get('blog', 'UserController@blog')->name('User.blog');
    Route::get('search_blogs', 'UserController@search_blogs')->name('User.search_blogs');

    Route::get('contact', 'UserController@contact')->name('User.contact');
    Route::post('contact_post', 'UserController@contact_post')->name('User.contact_post');

    Route::get('faq', 'UserController@faq')->name('User.faq');
    Route::get('service', 'UserController@service')->name('User.service');
    Route::get('tour_packages/{id}', 'UserController@tour_packages')->name('User.tour_packages');
    Route::get('error', 'UserController@error')->name('User.error');
    Route::get('gallery', 'UserController@gallery')->name('User.gallery');
    Route::post('ajax-post', 'UserController@ajax_post')->name('ajax-post');
    Route::get('seach_information','UserController@seach_information')->name('User.seach_information');
});
// -----------------------admin-------------------------------
Route::group(['prefix'=>'admin','namespace' => 'Admin','as' =>'admin.'], function () {
    Route::get('changestatus/{id}', 'customerController@changestatus')->name('changestatus');
    Route::get('/login', 'AdminLoginController@getlogin')->name('getlogin');
    Route::post('/login', 'AdminLoginController@postlogin')->name('postlogin');
    Route::get('/error', 'customerController@error')->name('error');
    Route::post('/avatar/{customer}', 'customerController@postavatar')->name('customer.avatar');
    Route::get('/forgot_password', 'AdminLoginController@get_password')->name('get_password');
    Route::post('/forgot_password', 'AdminLoginController@post_password')->name('post_password');
    Route::get('/password', 'AdminLoginController@get_code')->name('get_code');
    Route::post('/password', 'AdminLoginController@post_code')->name('post_code');
    Route::get('/register', 'RegisterController@get_register')->name('get_register');
    Route::post('/register', 'RegisterController@post_register')->name('post_register');
    Route::post('/change_pasword', 'AdminLoginController@post_change_pasword')->name('post_change_pasword');
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/', 'AdminLoginController@dashboard')->name('index');
        Route::resources([
            'category' => 'CategoryController',
            'tag' => 'TagController',
            'tour' => 'TourController',
            'customer' => 'customerController',
            'role' => 'RoleController',
            'gallery' => 'GalleryController',
            'role_assignment' => 'Role_AssignmentController',
            'contact' => 'contactController',
            'customer_service' => 'CustomerServiceController',
            'permission' => 'permissionController',

            // 'role_permission' => 'role_permissionController',
            'payment' => 'PaymentController',
            'order' => 'OrderController',
            'service' => 'ServiceController',
            'guide' => 'GuideController',
            'blog' => 'BlogController',
            'rating' => 'RatingController',
        ]);
         Route::get('orderview','OrderController@orderview')->name('orderview');
         Route::get('search_category','CategoryController@search_category')->name('search_category');
         Route::get('search_tag','TagController@search_tag')->name('search_tag');
         Route::get('search_payment','PaymentController@search_payment')->name('search_payment');
         Route::get('search_guide','GuideController@search_guide')->name('search_guide');
         Route::get('search_rating','RatingController@search_rating')->name('search_rating');
         Route::get('search_contact','contactController@search_contact')->name('search_contact');
         Route::get('search_tour','TourController@search_tour')->name('search_tour');
         Route::get('search_blog','BlogController@search_blog')->name('search_blog');
         Route::get('search_gallery','GalleryController@search_gallery')->name('search_gallery');
         Route::get('search_customer','customerController@search_customer')->name('search_customer');
         Route::get('search_customer_service','CustomerServiceController@search_customer_service')->name('search_customer_service');
         Route::get('search_role_assignment','Role_AssignmentController@search_role_assignment')->name('search_role_assignment');
         Route::get('seach_role','RoleController@seach_role')->name('seach_role');
         Route::get('search_service','ServiceController@search_service')->name('search_service');
         Route::get('seach_order','OrderController@seach_order')->name('seach_order');
         Route::get('seach_permission','OrderController@seach_permission')->name('seach_permission');

        Route::get('/logout', 'AdminLoginController@getLogout')->name('getlogout');
    });
});

resources/views/admin/page/Register.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base href="{{asset('public/admin')}}/">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="plugins/toastr.css">
  <link rel="stylesheet" href="plugins/toastr.min.css">
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <style>
    .is-invalid{
      background-image: none !important;
    }
  </style>
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a><b>Admin</b>LTE</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

    <form action="{{route('admin.post_register')}}" method="post">
        @csrf
        <div class="input-group mb-3">
          <input value="{{old('name')}}" class="form-control @error('name') is-invalid @enderror" id="usr" type="text" class="form-control" name="name" placeholder="Full name">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="form-group">
            <input value="{{old('date_of_birth')}}" class="form-control @error('date_of_birth') is-invalid @enderror" id="usr" name="date_of_birth" placeholder="Date Of Birth" onfocus="(this.type='date')" class="textbox-n" type="text">
        </div>
        <div class="form-group input-group">
          <input type="text" value="{{old('phone_number')}}" class="form-control @error('phone_number') is-invalid @enderror" id="usr" name="phone_number" placeholder="Phone number">
          <div class="input-group-append">
              <div class="input-group-text">
                <span class="fa fa-phone"></span>
              </div>
            </div>
        </div>
        <div class="form-group input-group">
          <input type="text" value="{{old('address')}}" class="form-control @error('address') is-invalid @enderror" id="usr" name="address" placeholder="Address">
          <div class="input-group-append">
              <div class="input-group-text">
                <span class="fa fa-map-marker"></span>
              </div>
            </div>
        </div>
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Email" name="email" value="{{old('email')}}" @error('email') is-invalid @enderror>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password" value="{{old('password')}}" @error('password') is-invalid @enderror>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Confirm password" name="confirm_password" value="{{old('confirm_password')}}" @error('confirm_password') is-invalid @enderror>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <label for="usr">Sex</label><br>
        <div class="form-group" style="display:flex"> 
            <input type="radio" id="male" name="sex" value="1" class="mr-2" checked>
            <label for="male" class="mr-2">Boy</label><br>
            <input type="radio" id="male" name="sex" value="2" class="mr-2">
            <label for="male">Girl</label><br>
        </div>
       
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" name="terms" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    <a href="{{route('admin.getlogin')}}" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.min.js"></script>
<script src="plugins/toastr.min.js"></script>
<script type="text/javascript">
  toastr.options = 
      {
          newestOnTop      : true,
          closeButton      : false,
          progressBar      : true,
          preventDuplicates: false,
          showMethod       : 'slideDown',
          timeOut          : 2000, //default timeout,
      };
  @if(Session::has('message'))
    var type = "{{ Session::get('alert-type', 'info') }}";
    switch(type){
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;
        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;
        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
  @endif
</script>
</body>
</html>

resources/views/admin/page/error.blade.php
@extends('admin/main')
@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="error-page">
          <h2 class="headline text-warning"> 404</h2>
  
          <div class="error-content">
            <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>
  
            <p>
              We could not find the page you were looking for.
              Meanwhile, you may <a href="../../index.html">return to dashboard</a> or try using the search form.
            </p>
  
            <form class="search-form">
              <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Search">
  
                <div class="input-group-append">
                  <button type="submit" name="submit" class="btn btn-warning"><i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
              <!-- /.input-group -->
            </form>
          </div>
          <!-- /.error-content -->
        </div>
        <!-- /.error-page -->
      </section>
      <!-- /.content
@endsection

resources/views/admin/page/forgotpassword.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Forgot Password</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base href="{{asset('public/admin')}}/">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  <link rel="stylesheet" href="plugins/toastr.css">
  <link rel="stylesheet" href="plugins/toastr.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>
    <form action="{{route('admin.post_password')}}" method="post">
      @csrf
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email" name="email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Request new password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <p class="mt-3 mb-1">
      <a href="{{route('admin.getlogin')}}">Login</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.min.js"></script>
<script src="plugins/toastr.min.js"></script>
<script type="text/javascript">
  toastr.options = 
      {
          newestOnTop      : true,
          closeButton      : false,
          progressBar      : true,
          preventDuplicates: false,
          showMethod       : 'slideDown',
          timeOut          : 2000, //default timeout,
      };
  @if(Session::has('message'))
    var type = "{{ Session::get('alert-type', 'info') }}";
    switch(type){
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;
        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;
        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
  @endif
</script>
</body>
</html>

resources/views/admin/page/login.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base href="{{asset('public/admin')}}/" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  <link rel="stylesheet" href="plugins/toastr.css">
  <link rel="stylesheet" href="plugins/toastr.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a><b>Admin</b>LTE</a>
  </div>
  @if (count($errors) >0)
         <ul>
             @foreach($errors->all() as $error)
                 <li class="text-danger"> {{ $error }}</li>
             @endforeach
         </ul>
     @endif

     @if (session('status'))
         <ul>
             <li class="text-danger"> {{ session('status') }}</li>
         </ul>
     @endif
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>
      <form action="{{ route('admin.postlogin') }}" method="POST">
        @csrf
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Email" name="email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember" name="remember" value="1">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
              <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="{{ route('admin.get_password') }}">I forgot my password</a>
      </p>
      <p class="mb-0">
      <a href="{{route('admin.get_register')}}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
</body>
<!-- /.login-box -->

<!-- jQuery -->
<script src="plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.min.js"></script>
<script src="plugins/toastr.min.js"></script>
<script type="text/javascript">
  toastr.options = 
      {
          newestOnTop      : true,
          closeButton      : false,
          progressBar      : true,
          preventDuplicates: false,
          showMethod       : 'slideDown',
          timeOut          : 2000, //default timeout,
      };
  @if(Session::has('message'))
    var type = "{{ Session::get('alert-type', 'info') }}";
    switch(type){
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;
        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;
        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
  @endif
</script>
</html>

resources/views/admin/page/mail.blade.php
mã xác nhận của bạn là:{{$code}}
<p>nhấn vào <a href="{{$route}}">Đây</a> để đổi mật khẩu.</p>

resources/views/admin/page/password.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
 <base href="{{url('public/admin')}}/">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  <link rel="stylesheet" href="plugins/toastr.css">
  <link rel="stylesheet" href="plugins/toastr.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
  <style type="text/css" media="screen">
    .error{
      color: red;
    }
  </style>
</head>
<body class="hold-transition login-page">
<div class="login-box" style="width: 400px">
  <div class="login-logo">
         <b>Admin</b>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>
    <form action="{{route('admin.post_code')}}" method="post">
        @csrf
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email" name="email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
          <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Nhập code" name="email_verified_at">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
          <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
          <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name=" comfim_password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember" name="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <!-- /.social-auth-links -->
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
<!-- jQuery -->
<script src="plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
<script src="plugins/toastr.min.js"></script>
<script type="text/javascript">
  toastr.options = 
      {
          newestOnTop      : true,
          closeButton      : false,
          progressBar      : true,
          preventDuplicates: false,
          showMethod       : 'slideDown',
          timeOut          : 2000, //default timeout,
      };
  @if(Session::has('message'))
    var type = "{{ Session::get('alert-type', 'info') }}";
    switch(type){
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;
        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;
        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
  @endif
</script>
</body>
</html>