routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => '', 'namespace' => 'User'], function () {
    Route::post('/l', 'UserController@postlogin')->name('User.postlogin');
    Route::get('login', 'UserController@login')->name('User.login');
    Route::post('/register', 'UserController@postpegister')->name('User.postpegister');
    Route::get('/logout', 'UserController@getlogout')->name('User.logout');
    Route::post('/change_pasword', 'UserController@post_change_pasword')->name('User.post_change_pasword');
    Route::post('/forgot_password', 'UserController@post_password')->name('User.post_password');
    Route::get('/forgotpass', 'UserController@forgotpass')->name('User.forgotpass');
    Route::post('/avatar/{customer}', 'UserController@postavatar')->name('customer.avatar');
    Route::get('/information', 'UserController@information')->name('User.information');

    Route::get('/code', 'UserController@get_code')->name('User.get_code');
    Route::post('/code', 'UserController@post_code')->name('User.post_code');

    Route::get('/', 'UserController@home')->name('User.home');
    Route::get('search_home', 'UserController@search_home')->name('User.search_home');
    Route::get('guideview','UserController@guideview')->name('guideview');


    Route::get('tour_details/{id}', 'UserController@tour_details')->name('User.tour_details');
    Route::post('tour_details_post', 'UserController@tour_details_post')->name('User.tour_details_post');
     Route::post('rating_post','UserController@rating_post')->name('User.rating_post');

    Route::get('blog_single/{id}', 'UserController@blog_single')->name('User.blog_single');
    Route::get('about', 'UserController@about')->name('User.about');
    Route::get('blog', 'UserController@blog')->name('User.blog');
    Route::get('search_blogs', 'UserController@search_blogs')->name('User.search_blogs');

    Route::get('contact', 'UserController@contact')->name('User.contact');
    Route::post('contact_post', 'UserController@contact_post')->name('User.contact_post');

    Route::get('faq', 'UserController@faq')->name('User.faq');
    Route::get('service', 'UserController@service')->name('User.service');
    Route::get('tour_packages/{id}', 'UserController@tour_packages')->name('User.tour_packages');
    Route::get('error', 'UserController@error')->name('User.error');
    Route::get('gallery', 'UserController@gallery')->name('User.gallery');
    Route::post('ajax-post', 'UserController@ajax_post')->name('ajax-post');
    Route::get('seach_information','UserController@seach_information')->name('User.seach_information');
});
// -----------------------admin-------------------------------
Route::group(['prefix'=>'admin','namespace' => 'Admin','as' =>'admin.'], function () {
    Route::get('changestatus/{id}', 'customerController@changestatus')->name('changestatus');
    Route::get('/login', 'AdminLoginController@getlogin')->name('getlogin');
    Route::post('/login', 'AdminLoginController@postlogin')->name('postlogin');
    Route::get('/error', 'customerController@error')->name('error');
    Route::post('/avatar/{customer}', 'customerController@postavatar')->name('customer.avatar');
    Route::get('/forgot_password', 'AdminLoginController@get_password')->name('get_password');
    Route::post('/forgot_password', 'AdminLoginController@post_password')->name('post_password');
    Route::get('/password', 'AdminLoginController@get_code')->name('get_code');
    Route::post('/password', 'AdminLoginController@post_code')->name('post_code');
    Route::get('/register', 'RegisterController@get_register')->name('get_register');
    Route::post('/register', 'RegisterController@post_register')->name('post_register');
    Route::post('/change_pasword', 'AdminLoginController@post_change_pasword')->name('post_change_pasword');
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/', 'AdminLoginController@dashboard')->name('index');
        Route::resources([
            'category' => 'CategoryController',
            'tag' => 'TagController',
            'tour' => 'TourController',
            'customer' => 'customerController',
            'role' => 'RoleController',
            'gallery' => 'GalleryController',
            'role_assignment' => 'Role_AssignmentController',
            'contact' => 'contactController',
            'customer_service' => 'CustomerServiceController',
            'permission' => 'permissionController',

            // 'role_permission' => 'role_permissionController',
            'payment' => 'PaymentController',
            'order' => 'OrderController',
            'service' => 'ServiceController',
            'guide' => 'GuideController',
            'blog' => 'BlogController',
            'rating' => 'RatingController',
        ]);
         Route::get('orderview','OrderController@orderview')->name('orderview');
         Route::get('search_category','CategoryController@search_category')->name('search_category');
         Route::get('search_tag','TagController@search_tag')->name('search_tag');
         Route::get('search_payment','PaymentController@search_payment')->name('search_payment');
         Route::get('search_guide','GuideController@search_guide')->name('search_guide');
         Route::get('search_rating','RatingController@search_rating')->name('search_rating');
         Route::get('search_contact','contactController@search_contact')->name('search_contact');
         Route::get('search_tour','TourController@search_tour')->name('search_tour');
         Route::get('search_blog','BlogController@search_blog')->name('search_blog');
         Route::get('search_gallery','GalleryController@search_gallery')->name('search_gallery');
         Route::get('search_customer','customerController@search_customer')->name('search_customer');
         Route::get('search_customer_service','CustomerServiceController@search_customer_service')->name('search_customer_service');
         Route::get('search_role_assignment','Role_AssignmentController@search_role_assignment')->name('search_role_assignment');
         Route::get('seach_role','RoleController@seach_role')->name('seach_role');
         Route::get('search_service','ServiceController@search_service')->name('search_service');
         Route::get('seach_order','OrderController@seach_order')->name('seach_order');
         Route::get('seach_permission','OrderController@seach_permission')->name('seach_permission');

        Route::get('/logout', 'AdminLoginController@getLogout')->name('getlogout');
    });
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $primaryKey = 'id';
    protected $fillable = [
        'UserID','PaymentID',
        'Status','Totalamount',
    ];
     public function  orderDetail(){
        return $this->hasMany('App\Models\OrderDetail','OrderID','id');
    }

     public function  customer(){
        return $this->hasOne('App\Models\customer','id','UserID');
    }
     public function  payment(){
        return $this->hasOne('App\Models\PaymentMethods','id','PaymentID');
    }
    public function add(){

        $model = Order::create([
            'UserID'=>request()->UserID,
            'PaymentID'=>request()->PaymentID,
            'Status'=>1,
            'Totalamount'=>request()->Totalamount,
        ]);
        return $model;
    }
    public function edit($id){

        $model =$this->where('id',$id)->update([
          'UserID'=>request()->UserID,
            'PaymentID'=>request()->PaymentID,
            'Status'=>request()->Status,
            'Totalamount'=>request()->Totalamount,
        ]);
        return $model;
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderDetail;
use Illuminate\Http\Request;
use App\Models\Tag;
use App\Models\Tour;
use App\Models\customer;
use App\Models\PaymentMethods;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $cats = Order::paginate(10);
        return view('admin.page.order.list',compact('cats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $paymentMethods = PaymentMethods::all();
          $customer = customer::all();
       return  view('admin.page.order.create',[
        'paymentMethods'=>$paymentMethods,
        'customer'=>$customer,
       ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Order $order)
    {

       $model =$order->add();

         if ($model) {
             return redirect()->route('order.index')->with('yes','them thanh cong ');
       }else{
             return redirect()->back()->with('no','toang ');
       }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }
     public function seach_order(Request $request)
    {
        $search =$request->get('search');
            $cats = Order::where('Name','like','%' .$search . '%')->paginate(10);
            return view('admin.page.order.list',compact('cats'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        $paymentMethods = PaymentMethods::all();
          $tag = Tag::all();
       return  view('admin.page.tour.create',[
        'paymentMethods'=>$paymentMethods,
        'tag'=>$tag,
       ]);
    }
    /**

     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $order->edit($order->id);

        return redirect()->route('order.index')->with('yes','caa nhat thanh cong!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
     public function orderview(Request $request){
        $id = $request->id;
        $order = OrderDetail::with('tour')->where('OrderID',$id)->first();
        // dd($order);
         // $customer = customer::all();

        return view('admin.page.orderDetail.show',[
            'order' => $order,
            // 'customer' => $customer,
        ]);
    }
}

resources/views/admin/page/order/create.blade.php
@extends('admin/main')
@section('content')
 <!-- Main content -->
 <div class="content-wrapper">
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">list</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">order</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section>
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Thêm mới</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="POST" action="{{ Route('admin.order.store') }}"  enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Tên danh mục </label>
                    <input type="text" class="form-control" id="CatName" name="Name" placeholder="Enter name">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Ngày tháng Năm sinh </label>
                   <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                    </div>
                    <input type="text" class="form-control" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask>
                  </div>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email </label>
                    <input type="email" class="form-control" id="CatName" name="Email" placeholder="Enter name">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Số điện thoại  </label>
                    <input type="number" class="form-control" id="Phone" name="Phone" placeholder="Enter name">
                  </div>
                 <div class="card-body pad p-0 ">
                   <label for="exampleInputEmail1"> Giới thiệu </label>
                   <div class="">
                     <textarea class="textarea" placeholder="Place some text here"
                              style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" name="Contactmethod"></textarea>
                   </div>
                 </div>


                  <div class="form-group">
                    <label for="exampleInputPassword1">Keyword Sell</label>
                    <input type="text" class="form-control" id="Keyword_Sell"  name="Keyword_Sell" placeholder="Password">
                  </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

              </form>
            </div>
            <!-- /.card -->

          </div>
    </section>
</div>
<script type="text/javascript">
$(document).ready(function () {
  bsCustomFileInput.init();
});

@endsection

resources/views/admin/page/order/list.blade.php
@extends('admin/main')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">list</h1>
                     </div><!-- /.col -->

          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">list</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
 <!-- Main content -->
   <section class="content">
      <div class="container-fluid">
        <!-- Info boxes -->
            <div class="card">

              <!-- /.card-header -->
              <div class="card-body ">
                <div class="table-responsive">
                  <table class="table m-0" id="example1">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>UserID</th>
                      <th>PaymentID</th>
                      <th>Status</th>
                      <th>Total amount</th>
                      <th>
                        <a href="{{ route('admin.order.create') }}" class="btn btn-xs btn-primary">Thêm</a>
                      </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($cats as $model)
                      <tr>
                        <td>{{ $model->id }}</td>
                            {{-- @foreach($model->customer as $val) --}}
                          <td>{{ $model->customer->name }}</td>
                             {{-- @endforeach --}}
                          <td>{{ $model->payment->Payment_type }}</td>
                            <td>{{ ($model->Status ==1)?"Hiện":"Ẩn"}}</td>
                            <td>{{ $model->Totalamount}}</td>
                            <td>

                              <form action="{{ route('admin.order.destroy',$model->id) }}" method="POST" accept-charset="utf-8">
                                @csrf @method('DELETE')
                                <div class="btn btn-xs btn-primary">
                                   <a data-toggle="modal" href="{{ route('admin.orderview') }}" class="text-white js_model" data-id="{{ $model->id }}"> Xem chi tiết</a>
                                </div>
                                <button type="submit" class="btn btn-xs btn-danger  " onclick="return confirm('Bạn có chắc muốn xóa không') " >Xóa</button>
                              </form>

                            </td>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
              </div>
              <!-- /.card-footer -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="modal fade" id="modal-order" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true" >
          <div class="modal-dialog " style=" width: 1000px;max-width: 1000px;">
            <div class="modal-content"style="width: 1000px;height : 800px;">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Chi tiết đơn hàng :<b class="data-id"></b></h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body " id="content_id">

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary|secondary|success|danger|warning|info|light|dark" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary|secondary|success|danger|warning|info|light|dark">Save changes</button>
              </div>
            </div>
          </div>
        </div>
@section('script')

<script>
  $(function(){
   $(".js_model").click(function(event){
      var data_id = $(this).attr("data-id");
        let url = $(this).attr('href');
        $.ajax({
            url: url,
            type: 'GET',
            data: {id:data_id},
            success: function(data){
                $("#content_id").html(data);
                $("#modal-order").modal('show');
            }
        });
   });
  });
</script>
@endsection

@endsection
@section('data_table')
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
@endsection

resources/views/admin/page/order/update.blade.php
@extends('admin/main')
@section('content')
 <!-- Main content -->
 <div class="content-wrapper">
  <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">list</h1>
                     </div><!-- /.col -->

          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">list</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section>
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">cập nhật</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="POST" action="{{ route('order.update',['order'=>$order->id]) }}"  enctype="multipart/form-data">
                @csrf  @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Tên danh mục </label>
                    <input type="text" class="form-control" id="CatName" name="CatName" placeholder="Enter name" value="{{ $category->CatName}}">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input" id="exampleInputFile" name="upload">
                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                      </div>

                      <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Keyword Sell</label>
                    <input type="text" class="form-control" id="Keyword_Sell"  name="Keyword_Sell" placeholder="Password" value="{{ $category->Keyword_Sell}}">
                  </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

              </form>
            </div>
            <!-- /.card -->

          </div>
    </section>
</div>
<script type="text/javascript">
$(document).ready(function () {
  bsCustomFileInput.init();
});

@endsection